dist: focal

sudo: required

script:
  - pwd
  - whoami
  - wget -O ~/ccache.cache.tar.gz https://github.com/puteulanus/flippy-kernel-build/releases/download/5.18.15_ccache/ccache.cache.tar.gz
  - tar zxf ~/ccache.cache.tar.gz -C ~/
  - ls ~/.ccache
  - sudo apt-get update
  - sudo apt-get remove -y erlang* mysql* wireless-regdb xserver-common xserver-xorg-core xvfb gce-compute-image-packages google-compute-engine-oslogin
  - git clone https://github.com/armbian/build
  - cd build
  - sed -i 's#git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git#https://github.com/puteulanus/linux-5.18.y#' lib/configuration.sh
  - mkdir ~/{boot,modules}
  - sed -i '/Creating packages/amake ARCH=arm64 INSTALL_PATH=~/boot install' lib/compilation.sh
  - sed -i '/Creating packages/amake ARCH=arm64 INSTALL_MOD_PATH=~/modules modules_install' lib/compilation.sh
  - sed -i 's/LOCALVERSION="-${LINUXFAMILY}"/LOCALVERSION=""/' lib/compilation.sh
  - sed -i 's/LOCALVERSION="-$LINUXFAMILY"/LOCALVERSION=""/' lib/compilation.sh
  - sed -i "/'PRE_INSTALL_KERNEL_DEBS'/iCHOSEN_KERNEL='linux-image-current'" lib/distributions.sh
  - rm -f patch/kernel/station-p2-current/*.patch
  - mkdir userpatches
  - echo 'KERNELBRANCH="branch:main"' > userpatches/lib.config
  - wget -O userpatches/linux-media-current.config 'https://raw.githubusercontent.com/unifreq/arm64-kernel-configs/main/config-5.18.14-flippy-75%2B'
  - cat ../kernel-config.txt >> userpatches/linux-media-current.config
  - ./compile.sh  BOARD=station-p2 BRANCH=current RELEASE=bullseye BUILD_MINIMAL=yes BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,gpg,img SKIP_BOOTSPLASH=yes AUFS=no EXTRAWIFI=no BUILD_KSRC=no KERNEL_KEEP_CONFIG=no
  - losetup -P /dev/loop20 output/images/*.img
  - mkdir ~/armbian
  - mount /dev/loop20p1 ~/armbian
  - cp ~/armbian/boot/{uInitrd-*,initrd.img-*} ~/boot
  - cd ~/boot
  - filename=$(ls uInitrd-*)
  - tar zcvf boot-${filename:8}.tar.gz *
  - cd ~/modules/lib/modules/
  - tar zcvf modules-${filename:8}.tar.gz *
